-- Create meditation_sessions table
CREATE TABLE IF NOT EXISTS meditation_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes INTEGER NOT NULL,
    interval_minutes INTEGER,
    distraction_count INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create trigger to update updated_at timestamp
CREATE TRIGGER update_meditation_sessions_updated_at
    BEFORE UPDATE ON meditation_sessions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
