-- Create journal_entries table
CREATE TABLE IF NOT EXISTS journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    gratitude TEXT,
    gifts TEXT,
    strategy TEXT,
    strategy_checks JSONB,
    best_day TEXT,
    image_url TEXT,
    workout_notes TEXT,
    workout_category VARCHAR(50) CHECK (workout_category IN ('upper_body', 'lower_body', 'endurance')),
    deep_flow_activity TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create scorecards table
CREATE TABLE IF NOT EXISTS scorecards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    journal_entry_id BIGINT REFERENCES journal_entries(id) ON DELETE CASCADE,
    mood_score INTEGER CHECK (mood_score >= 0 AND mood_score <= 10),
    energy_score INTEGER CHECK (energy_score >= 0 AND energy_score <= 10),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create triggers to update updated_at timestamp
CREATE TRIGGER update_journal_entries_updated_at
    BEFORE UPDATE ON journal_entries
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_scorecards_updated_at
    BEFORE UPDATE ON scorecards
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
