-- Create schedule_blocks table
CREATE TABLE IF NOT EXISTS schedule_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    phase TEXT NOT NULL,
    activity TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add RLS policies
ALTER TABLE schedule_blocks ENABLE ROW LEVEL SECURITY;

-- Create a trigger to update the updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_schedule_blocks_updated_at
    BEFORE UPDATE ON schedule_blocks
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- Add recurring meditation blocks (weekdays 30 min, weekends 60 min)
INSERT INTO schedule_blocks (day_of_week, activity, notes, phase) VALUES
  -- Weekday meditation (Mon-Fri)
  (1, 'Meditation', 'Daily meditation practice', 'first_thing'),
  (2, 'Meditation', 'Daily meditation practice', 'first_thing'),
  (3, 'Meditation', 'Daily meditation practice', 'first_thing'),
  (4, 'Meditation', 'Daily meditation practice', 'first_thing'),
  (5, 'Meditation', 'Daily meditation practice', 'first_thing'),
  -- Weekend meditation (Sat-Sun)
  (6, 'Meditation', 'Extended weekend meditation', 'first_thing'),
  (0, 'Meditation', 'Extended weekend meditation', 'first_thing');

-- Add workout schedule
INSERT INTO schedule_blocks (day_of_week, activity, notes, phase) VALUES
  (1, 'Workout', 'Upper Body Lift', 'early_morning'),
  (2, 'Workout', 'Lower Body Lift', 'early_morning'),
  (3, 'Workout', 'Run', 'early_morning'),
  (4, 'Workout', 'Upper Body Lift', 'early_morning'),
  (5, 'Workout', 'Lower Body Lift', 'early_morning'),
  (6, 'Workout', 'Run', 'early_morning'),
  (0, 'Workout', 'Rowing and Yoga', 'early_morning');

-- Add article writing blocks
INSERT INTO schedule_blocks (day_of_week, activity, notes, phase) VALUES
  (1, 'Writing', 'Medium Article', 'morning'),
  (2, 'Writing', 'Medium Article', 'morning'),
  (3, 'Writing', 'Medium Article', 'morning'),
  (4, 'Writing', 'Medium Article', 'morning'),
  (5, 'Writing', 'Medium Article', 'morning'),
  (6, 'Writing', 'Medium Article', 'morning'),
  (0, 'Writing', 'LinkedIn Article', 'morning');

-- Add flexible deep work blocks
INSERT INTO schedule_blocks (day_of_week, activity, notes, phase) VALUES
  -- Deep Work 1 (flexible, decided day of)
  (1, 'Deep Work', 'Deep Work Session 1 - Flexible', 'mid_morning'),
  (2, 'Deep Work', 'Deep Work Session 1 - Flexible', 'mid_morning'),
  (3, 'Deep Work', 'Deep Work Session 1 - Flexible', 'mid_morning'),
  (4, 'Deep Work', 'Deep Work Session 1 - Flexible', 'mid_morning'),
  (5, 'Deep Work', 'Deep Work Session 1 - Flexible', 'mid_morning'),
  -- Deep Work 2 (flexible, decided day of)
  (1, 'Deep Work', 'Deep Work Session 2 - Flexible', 'second_wind'),
  (2, 'Deep Work', 'Deep Work Session 2 - Flexible', 'second_wind'),
  (3, 'Deep Work', 'Deep Work Session 2 - Flexible', 'second_wind'),
  (4, 'Deep Work', 'Deep Work Session 2 - Flexible', 'second_wind'),
  (5, 'Deep Work', 'Deep Work Session 2 - Flexible', 'second_wind');

-- Add evening activities
INSERT INTO schedule_blocks (day_of_week, activity, notes, phase) VALUES
  -- Evening meal
  (1, 'Meal', 'Evening meal', 'dinner'),
  (2, 'Meal', 'Evening meal', 'dinner'),
  (3, 'Meal', 'Evening meal', 'dinner'),
  (4, 'Meal', 'Evening meal', 'dinner'),
  (5, 'Meal', 'Evening meal', 'dinner'),
  (6, 'Meal', 'Evening meal', 'dinner'),
  (0, 'Meal', 'Evening meal', 'dinner'),
  -- Evening coding
  (1, 'Coding', 'Evening commit', 'coding'),
  (2, 'Coding', 'Evening commit', 'coding'),
  (3, 'Coding', 'Evening commit', 'coding'),
  (4, 'Coding', 'Evening commit', 'coding'),
  (5, 'Coding', 'Evening commit', 'coding'),
  (6, 'Coding', 'Evening commit', 'coding'),
  (0, 'Coding', 'Evening commit', 'coding'),
  -- Evening entertainment
  (1, 'Entertainment', 'Evening relaxation', 'entertainment'),
  (2, 'Entertainment', 'Evening relaxation', 'entertainment'),
  (3, 'Entertainment', 'Evening relaxation', 'entertainment'),
  (4, 'Entertainment', 'Evening relaxation', 'entertainment'),
  (5, 'Entertainment', 'Evening relaxation', 'entertainment'),
  (6, 'Entertainment', 'Evening relaxation', 'entertainment'),
  (0, 'Entertainment', 'Evening relaxation', 'entertainment');
